### ISSUE TITLE
Sensitive details are public

### ISSUE THREAD

**Issue by djessup** [DaniG2k/Scripts#1]
Hi there,

I came across this repo while doing a Google search for Funnelback install details and saw this file which contains some sensitive information like admin logins to the download server and a license key. Just thought I'd drop a line to let you know in case this isn't intentional.

https://github.com/DaniG2k/Scripts/blob/master/fb-installer-script.sh

Cheers,
David.

**Comment by DaniG2k** [comment]
Hi David,

Thanks for the heads up!

Kind regards,
Daniele
